from enum import Enum


class Types(Enum):
    button_email = (0, '邮件图标')
    button_receive_all = (1, '一键领取')
    button_get = (2, '领取')
    button_weituo = (3, '委托图标')
    button_weituo_again = (4, '再次委托')
    button_more = (5, '更多')
    button_manyouqianzheng = (6, '漫游签证')
    button_manyouqianzheng_get = (7, '助战奖励')
    button_shixun = (8, '实训')
    button_xunli = (9, '巡礼')
    button_xunli_renwu = (10, '巡礼任务')
    button_xunli_jiangli = (11, '巡礼奖励')
    button_xunli_renwu_week = (12, '巡礼任务周')
    button_xunli_renwu_version = (13, '巡礼任务期')
    button_again = (14, '再来一次')
    button_leave = (15, '退出关卡')
    button_sure = (16, '确定')
    button_cancel = (17, '取消')
    button_start = (18, '开始挑战')
    button_challenge = (19, '挑战')
    button_teleport = (20, '传送')
    button_xingqiong = (21, '星琼')
    button_fuel = (22, '燃料')
    button_shixun_get = (23, '实训领取')
    button_extra_fuel = (24, '后备开拓力')
    text_success = (25, '挑战成功')
    text_fail = (26, '挑战失败')
    text_quantity = (27, '取出数量(后备力)')
    text_enough = (28, '满500实训点')
    NZHEJ = (29, '拟造花萼(金)')
    NZHEJ_JY = (30, '经验材料')
    NZHEJ_GZ = (31, '光锥材料')
    NZHEJ_Q = (32, '钱')
    NZHEC = (33, '拟造花萼(赤)')
    NZHEC_HM_SRCD = (34, '毁灭_收容舱段')
    NZHEC_HM_LYJ = (35, '毁灭_鳞渊境')
    NZHEC_CH_ZYCD = (36, '存护_支援舱段')
    NZHEC_CH_KLKYSLY = (37, '存护_克劳克影视乐园')
    NZHEC_XL_CJXY = (38, '巡猎_城郊雪原')
    NZHEC_FR_BYTL = (39, '丰饶_边缘通路')
    NZHEC_FR_SY = (40, '丰饶_绥园')
    NZHEC_ZS_MDZ = (41, '智识_铆钉镇')
    NZHEC_TX_JXJL = (42, '同谐_机械聚落')
    NZHEC_TX_BRMJD_MJ = (43, '同谐_白日梦酒店_梦境')
    NZHEC_XW_DKQ = (44, '虚无_大矿区')
    NZHEC_XW_DDS = (45, '虚无_丹鼎司')
    NZXY = (46, '凝滞虚影')
    NZXY_KH = (47, '空海之形')
    NZXY_XF = (48, '巽风之形')
    NZXY_ML = (49, '鸣雷之形')
    NZXY_YH = (50, '炎华之形')
    NZXY_FM = (51, '锋芒之形')
    NZXY_SJ = (52, '霜晶之形')
    NZXY_HG = (53, '幻光之形')
    NZXY_BL = (54, '冰棱之形')
    NZXY_ZE = (55, '震厄之形')
    NZXY_YO = (56, '偃偶之形')
    NZXY_NS = (57, '孽兽之形')
    NZXY_FZ = (58, '燔灼之形')
    NZXY_TR = (59, '天人之形')
    NZXY_YF = (60, '幽府之形')
    NZXY_BN = (61, '冰酿之形')
    NZXY_JZ = (62, '焦炙之形')
    NZXY_CN = (63, '嗔怒之形')
    QSSD = (64, '侵蚀隧洞')
    QSSD_SF = (65, '冰风套')
    QSSD_XQ = (66, '物理击破套')
    QSSD_PB = (67, '治疗枪手套')
    QSSD_RZ = (68, '铁卫量子套')
    QSSD_SS = (69, '圣骑士雷套')
    QSSD_YY = (70, '火虚套')
    QSSD_YS = (71, '莳者信使套')
    QSSD_YM = (72, '大公系囚套')
    QSSD_MQ = (73, '死水钟表匠套')
    LZYX = (74, '历战余响')
    LZYX_HMDKD = (75, '毁灭的开端')
    LZYX_HCDLM = (76, '寒潮的落幕')
    LZYX_BSDSS = (77, '不死的神实')
    LZYX_ZXDJY = (78, '蛀星的旧靥')
    LZYX_CMDZL = (79, '尘梦的赞礼')
    button_zhinan = (80, '指南')
    button_suoying = (81, '生存索引')
    c_yaliluo6 = (82, '雅利洛六号')
    c_luofuxianzhou = (83, '罗浮仙舟')
    c_pinuokangni = (84, '匹诺康尼')
    button_follow = (85, '跟踪')
    NZHEC_XL_SLDRSHXHC = (86, '巡猎_苏乐达热砂海选会场')
    NZXY_ZS = (87, '职司之形')
    text_no_power = (88, '开拓力补充')
    button_get_all = (89, '全部领取(邮件特供)')
    text_yueka = (90, '月卡标识')
    QSSD_YQ = (91, '追击击破套')
    NZHEC_ZS_PNKNDJY = (92, '智识_匹诺康尼大剧院')

    def __init__(self, number, desc_zn):
        self.number = number
        self.desc_zn = desc_zn

    @property
    def get_number(self):
        return self.number

    @property
    def get_desc_zn(self):
        return self.desc_zn
